# Generated by Django 4.2.8 on 2023-12-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("flag", models.URLField(max_length=255)),
                ("currency", models.CharField(max_length=5)),
            ],
        ),
    ]
