# Generated by Django 4.2.8 on 2023-12-12 08:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("countries", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name": "Country", "verbose_name_plural": "Countries"},
        ),
    ]
