# Generated by Django 4.2.8 on 2023-12-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("countries", "0002_alter_country_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
