# Generated by Django 4.2.8 on 2023-12-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("countries", "0003_alter_country_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="currency",
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
